DROP FUNCTION IF EXISTS FtotalSub() CASCADE;
DROP FUNCTION IF EXISTS fact(i integer, g integer) CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__sub_valFix() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__sub_valHab() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__Etatique() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__Regionale() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__Metropolitaine() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__Communale() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__Commune() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__Metropole() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__Region() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__Pays() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__Eau() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__Jus() CASCADE;
DROP FUNCTION IF EXISTS Heritage_total__Alcool() CASCADE;
DROP FUNCTION IF EXISTS prixLocal( l integer, r integer) CASCADE;
DROP FUNCTION IF EXISTS subLocal( l integer, r integer, OUT subLocal_table(val_const, val_const_hab, val_mult, val_mult_hab, val_upperCap, val_lowerCap)) CASCADE;
DROP FUNCTION IF EXISTS FtotalSubRegion(g integer) CASCADE;
DROP FUNCTION IF EXISTS FtotalSubRegionLiquide(g integer,l integer ) CASCADE ;
/*
DROP FUNCTION IF EXISTS CASCADE 
DROP FUNCTION IF EXISTS CASCADE 
DROP FUNCTION IF EXISTS CASCADE 
DROP FUNCTION IF EXISTS CASCADE 
DROP FUNCTION IF EXISTS CASCADE 
DROP FUNCTION IF EXISTS CASCADE 
DROP FUNCTION IF EXISTS CASCADE 
DROP FUNCTION IF EXISTS CASCADE 
DROP FUNCTION IF EXISTS CASCADE 
DROP FUNCTION IF EXISTS CASCADE 
DROP FUNCTION IF EXISTS CASCADE 
*/