
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.*;
public class App {
   

    public static void main(String[] args) {
        Graph graph= new Graph();
        UiConsole UI= new UiConsole(graph);
        UI.initStations();
        UI.displayRoute();

    }
}


